admin-password: ""
allow-private-cidrs: false
api-addr: :1633
block-hash: ""
block-time: "15"
bootnode: []
bootnode-mode: false
cache-capacity: "1000000"
cache-retrieval: true
chain-enable: true
chequebook-enable: true
clef-signer-enable: false
clef-signer-endpoint: ""
clef-signer-ethereum-address: ""
config: /Users/umer/.bee.yaml
cors-allowed-origins: []
data-dir: /Users/umer/.bee
db-block-cache-capacity: "33554432"
db-disable-seeks-compaction: false
db-open-files-limit: "200"
db-write-buffer-size: "33554432"
debug-api-addr: :1635
debug-api-enable: false
full-node: false
gateway-mode: false
help: false
mainnet: true
nat-addr: ""
network-id: "10"
p2p-addr: :1634
p2p-ws-enable: false
password: ""
password-file: ""
payment-early-percent: 50
payment-threshold: "100000000"
payment-tolerance-percent: 25
postage-stamp-address: ""
pprof-mutex: false
pprof-profile: false
price-oracle-address: ""
resolver-options: []
restricted: false
resync: false
static-nodes: []
swap-deployment-gas-price: ""
swap-enable: true
swap-endpoint: ws://localhost:8546
swap-factory-address: ""
swap-initial-deposit: "10000000000000000"
swap-legacy-factory-addresses: []
token-encryption-key: ""
tracing-enable: false
tracing-endpoint: 127.0.0.1:6831
tracing-host: ""
tracing-port: ""
tracing-service-name: bee
transaction: ""
use-postage-snapshot: false
verbosity: info
warmup-time: 20m0s
welcome-message: ""

